### ISSUE TITLE
Update for Big Sur design changes

### ISSUE THREAD

**Issue by devantler** [othyn/github-folder-icon-macOS#1]
Hi, will you make an update, so to include a version that matches the Big Sur folder icon?

**Comment by devantler** [comment]
<img width="92" alt="image" src="https://user-images.githubusercontent.com/26203420/90884768-a4643000-e3b0-11ea-81ee-081eeea2370f.png">
As you can see they don't look the same :-)

**Comment by othyn** [comment]
Can do!

I've scoured the web and I can't find the default empty folder icon that I can use as a template. I don't have Big Sur yet and don't plan to until its out as a stable release.

Please can you extract the default folder `icns` from your install and share it here?

**Comment by devantler** [comment]
Hmm, they have made it quite a bit harder to do this, as they do not share the actual icns with the correct style. From reading on a forum, I found this:

"Big Sur does not use the /S/L/CS/Coretypes.bundle folder icons anymore to display the various System Folder icons. Instead, it uses a [generic] template folder icon (a PNG image in various pixel sizes, locked inside /S/L/CS/IconsetResources.bundle) and adds various font glyphs on top of it to denote the different types of System folder, or leaves the folder blank in the middle for new/basic folders, like the look of the old GenericFolderIcon.icns file. You can change the look of this background folder. Still, the light blue font glyph (eg. for Applications, Library, Utilities, Home etc.) will remain being displayed in the center of the folder, so that aspect of customizing isn’t currently possible (see footnotes)."

The files in there do not look exactly like the actual icons, and to my eye resembles the old icons much more. So I do not think it helps much. 
I think it would be wise to wait till someone else figures out how to recreate the icons, as it sadly seems like a lot of work :S

[Archive.zip](https://github.com/othyn/github-folder-icon-macOS/files/5337349/Archive.zip)

**Comment by othyn** [comment]
Yeah, those are the old icons 😕

Well damn! We may have to wait until there is a known method for the default folder extraction. What was the forum in which you found the above excerpt from? Just so we can monitor it for future movement.

**Comment by devantler** [comment]
I think this was it:
https://forums.macrumors.com/threads/macos-11-all-the-little-things.2242170/page-18?post=28742894#post-28742894

**Comment by othyn** [comment]
Cheers, I suppose we'll just have to wait until Big Sur's release to see what's up, so I can take a peek into the process a little more with how macOS 11 deals with this, as I need to wait for release. That and following the thread to see if anyone has any breakthroughs in getting the folder icon extracted.

**Comment by othyn** [comment]
Appears this thread had the quote on it:

https://forums.macrumors.com/threads/changing-folder-icons-big-sur.2245940/?post=28725160#post-28725160

And for Beta 6 here:

https://forums.macrumors.com/threads/changing-folder-icons-big-sur.2245940/?post=28986712#post-28986712

Is there any way you can follow those steps to extract the default folder icons from your Big Sur installation?

**Comment by devantler** [comment]
I extracted it using a tool that did not require disabling sap and all this stuff. I hope everything you need is there! 

I can see there are the light and dark folders along with some fancy purple and pink versions. I think the latter would make for wonderful GitHub folder icons, so if you'd like to provide those, it would be awesome!! :-D
https://github.com/niem94/big-sur-folder-icons
